### PR TITLE
New template for iPhone and improvements

### PR DESCRIPTION
**Pull request by Ashernor**
- Handling templates for other phones, you just have to create a corresponding template_YOURPHONE.svg file and use the -m argument in the script ; the crops file for you model will then be generated
- Using MacOS and Linux handle to open the browser instead of testing browser in Linux and Chromium path on MacOS
- For the HP detection, the command now uses a regular expression to removes letters, because of 'HP' translations

### CODE REVIEW

**Comment by chrisnoisel** [comment]
- test.png should be removed
- why resizing the image each time ? (without preserving ratio ?)

**Comment by Ashernor** [comment]
For the resizing it's because it's easiest to move the elements on the SVG on other sizes by using yours which is in 1920*1080.

**Comment by Ashernor** [comment]
test.png removed.

**Comment by Ashernor** [comment]
New svg !

**Comment by Ashernor** [comment]
@chrisnoisel I just resolved the conflicts

**Comment by chrisnoisel** [comment]
- it breaks the script (CP value not retrieved)
- I think it's better if the repo stores the fewer device-dependent config files. The SVGs have all the informations, "crop" is automatically generated on first execution that's why I added the gitignore in my last commit (screen.png gets it too). Maybe a header line in "crops" can indicate which device it belongs to so import.sh knows if it's still relevant on each execution (if not, delete then generate). So only one "crops" get generated per user, no fancy suffixes ?
- why 'IMG="$DIR/resize.png"' ? "screen_iphone6.png" seems used in template_iphone6.svg. Again, maybe we should keep only one "screen.png" ?

**Comment by Ashernor** [comment]
@chrisnoisel all your remarks have been taking into account.

**Comment by chrisnoisel** [comment]
thanks !

**Pull request merged**
